name: Deploy Vue

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy gh-pages
      run: |
        sh deploy.sh
